# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseMap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	# Pods for BaseMap
	pod 'SWXMLHash', '~> 3.0.0'
  target 'BaseMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseMapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
